Update test for -n flag

diff --git a/bootstrapBeaconShard b/bootstrapBeaconShard
--- a/bootstrapBeaconShard
+++ b/bootstrapBeaconShard
@@ -7,8 +7,8 @@ dataDir="/datastore/incognito/node_data_"
 fileDir="/root/"
 
 # Checking for flags
-if [ $# -gt -1 ]; then
-	echo "Error: Invalid number of arguments.\n 
+if ! [ $# =~ ^[0-9]+$ ]; then
+	echo -e "Error: Invalid number of arguments.\n 
     Format arguements as [-n # for node_data_n REQUIRED, -b if you want the beacon bootstrapped and/or -s # for the shard you want bootstrapped].\n
     Exiting now\n\n"
  	exit 1
@@ -18,6 +18,11 @@ while getopts 'n:bs:' OPTION; do
   case "$OPTION" in
     n)
       n="$OPTARG"
+      if ! [ $n =~ ^[0-9]+$ ]; then
+        echo -e "Error: -n requires an integer"
+        exit 1
+      fi
+      
       echo -e "\nPreparing inc_mainnet_$n \n"
       docker stop inc_mainnet_$n
       ;;
